kind: PersistentVolume
apiVersion: v1
metadata:
  name: userdb-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/docker/volumes/users_data"